### ISSUE TITLE
`$TimerPwm` hides inner timer 

### ISSUE THREAD

**Issue by koutoftimer** [Rahix/avr-hal#135]
Implementation of [timer macro](https://github.com/Rahix/avr-hal/blob/master/avr-hal-generic/src/pwm.rs#L52) hides owned underling timer data and prevents access to `RegisterBlock`

**Comment by Rahix** [comment]
This is intentional.  HAL abstractions must not provide access to the underlying peripheral to ensure sound design.  Otherwise the abstraction cannot reason about the state of the peripheral at all which makes it impossible to write robust code.

The only use-case where you'd need access to the peripheral directly is one where the HAL abstraction is not powerful enough.  Instead of hacking the existing abstractions to somehow work for your needs, the proper solution would be to either augment existing HAL code to support your use-case or to create a second, separate abstraction which handles your application specifically.
