### ISSUE TITLE
"uno-timer" example no longer works

### ISSUE THREAD

**Issue by gregoryholder** [Rahix/avr-hal#499]
I can't quite tell where the break is happening, but the [uno-timer](https://github.com/Rahix/avr-hal/blob/c1b78e9014e3d45c0b90a74bb151b1ec0ef6819f/examples/arduino-uno/src/bin/uno-timer.rs) example no longer seems to work. It seems to be due to a combination of `Pin<Output, Dynamic>`, calling the toggle method and using `MaybeUninit`. 

If I change the pin declaration to a static pin `Pin<Output, PB7>` and remove the`.downgrade()`, the example works again. 

I've also tried moving the interrupt code into a main loop, but again it only works with a static pin or with separate `set_high/set_low` calls.

This works:
```rust
// in main()
loop {
    let state = unsafe {
        &mut *INTERRUPT_STATE.as_mut_ptr()
    };

    state.blinker.set_high();
    delay_ms(100);
    state.blinker.set_low();
    delay_ms(100);
}
```

But this doesn't:
```rust
// in main()
loop {
    let state = unsafe {
        &mut *INTERRUPT_STATE.as_mut_ptr()
    };

    state.blinker.toggle();
    delay_ms(100);
}
```
---

I'm still new to low level Rust, so I'd appreciate any (~raw~)pointers with regard to diagnosing this kind of issue. It might be related to #286.

**Comment by Rahix** [comment]
It seems the `out_toggle` implementation between static pins and dynamic pins differ:

#### Static Pin
https://github.com/Rahix/avr-hal/blob/c1b78e9014e3d45c0b90a74bb151b1ec0ef6819f/avr-hal-generic/src/port.rs#L723-L725

#### Dynamic Pin
https://github.com/Rahix/avr-hal/blob/c1b78e9014e3d45c0b90a74bb151b1ec0ef6819f/avr-hal-generic/src/port.rs#L645-L651

The dynamic pin impl is writing to the `PORT` register instead of the `PIN` register.  This seems to be a regression from commit 063f845a0940a865c591d2156cd0a8267e2346a8.  Paging @LuigiPiucco :)

@gregoryholder, can you change `[<port $name:lower>]` to `[<pin $name:lower>]` in L647 and test whether that fixes the problem?

**Comment by LuigiPiucco** [comment]
This seems a bit strange, at least upon first glance. The dynamic version is not working, but (in theory) the one that's wrong is the static one (out methods should write to port, not pin, since pin is for reading when input, no?). Also, I notice some of these use `.write` and others `.modify`. I didn't pay much mind to it before (just copy-pasted) but maybe it's similar to  #494, where the former causes unintended consequences. I'll look into it and take this opportunity to apply a usage comment like the one for the ADC. Just note I don't have an Uno right now, so I'll try to reproduce on the Mega2560. If I can't I'll ask @gregoryholder to check the fix when I finish.

**Comment by gregoryholder** [comment]
I can confirm this happenes on a mega2560, that's what I was using
initially. To sanity check I cloned the latest version of the repo and ran
the unchanged example on an Uno.

**Comment by LuigiPiucco** [comment]
I'm reasonably sure on the solution ([here](https://github.com/LuigiPiucco/avr-hal/commit/0671418c758cc87c5deae417f338aeecdccf14a0)), but I can't test right now, so I'll wait before opening a PR.

Reading through #284 I am a bit confused, and I think the source of this bug was similar confusion about the behavior of registers in Rust. The code of `out_toggle` before the mentioned issue was:
```rust
$<port pointer wrapper>.modify(|r, w| {
    w.bits(r.bits() | self.mask) // (1 << $pin_num) as the mask for the static version
})
```
... which, looking closely, is what `out_set` expands to now. And doing some truth table analysis, this can only ever _set_ the bit, but never clear it. For toggle, we want something that does both, kind of like this:

```rust
match cur_bit {
    0b1 => 0b0, // Clear
    0b0 => 0b1, // Set
}
```

The proposed solution was:

```rust
$<port pointer wrapper>.write(|w| w.bits(self.mask))
```

... which could work, _if_ the behavior of `.write` was to flip from the port every bit where the mask is 1. But I'm pretty sure it just writes whatever you pass unchanged, including the 0s. The only exception I know is if you use single field access instead of a bitmask, when it assumes the reset value for anything you don't touch. So we do need `.modify`, at least to keep other bits unmodified.

Another issue is what function to use between the current value and the mask to toggle the one bit, keeping others. The answer is an XOR. I think in this case, the notation of C makes thinks a bit more evident:

```c
PORTD |= 1 << 3;    // Set bit 3
PORTD &= ~(1 << 3); // Clear bit 3
PORTD ^= 1 << 3;    // Toggle bit 3, for every 0 in the mask it does not change PORTD, but for the 1 it flips
```

So we end up with:

```rust
$<port pointer wrapper>.modify(|r, w| {
    w.bits(r.bits() ^ self.mask)
})
```

Please double check the logic here, it does seem easy to get wrong. There's also some analysis of assembly in #284, but due to the reasons above I think it doesn't apply. I can check the output of my suggestion if needed, though.

**Comment by Rahix** [comment]
@LuigiPiucco, writing a single 1 bit into the PIN register toggles the pin:

![image](https://github.com/Rahix/avr-hal/assets/7566996/72cae1c8-ef5b-41c5-99b6-7cfd4ababd8e)

That's why I was suggesting that the problem is writing to PORT instead of PIN. :)

**Comment by LuigiPiucco** [comment]
Ok, I did not know that. That's an interesting piece of information. However, unlike in #284, the compiler never produces `sbi` for me (not even in the static case). It's always `ldi`-`out`. The XOR code as I suggested compiles down to `in`-modify-`out` on the PORTx register. Without this toggle feature on the PINx register, I think that's as good as we'd get. But since it exists, we can rule out the `in` and `eor`. Do you prefer to change to that or keep the more recognizable XOR approach? Also, I think the static case may be possible to optimize with assembly (guaranteeing it translates to `sbi`), but not the dynamic one, since `sbi` encodes the bit and register into the opcode.

**Comment by Rahix** [comment]
We should use the "write bit to PIN reg to toggle" trick.  Two reasons:

1. It's faster than a read-modify-write cycle
2. It's atomic.  The read-modify-write cycle of writing to PORT would require to be put in a critical section to avoid a nasty race condition.  This would be even more overhead.

---

> However, unlike in https://github.com/Rahix/avr-hal/issues/284, the compiler never produces sbi for me (not even in the static case). It's always ldi-out.

I assume you were testing the _current_ implementation?  That one indeed cannot be optimized to `sbi` anymore.  `sbi` is emitted for a static version of the read-modify-write cycle.  But we didn't want to rely on this optimization for correctness, so we decided to move to the current approach which leads to `ldi`-`out`.  It matters for correctness for the same race-condition mentioned above.

**Comment by LuigiPiucco** [comment]
@Rahix I updated [my branch](https://github.com/LuigiPiucco/avr-hal/tree/fix-toggle) and I am writing the pull request with details. I deviated from just changing port to pin, so I'll comment here if you want to start checking it before I write the detailed explanation. I wrote it in a way that the optimal single `sbi`/`cbi` is always generated for setting and toggling, even in lower optimization levels. It's also "safer" (in the sense that it uses less `unsafe {}`s). The getters generate more code than the setters, but I think comparing to the prior implementation there's negative balance. But maybe there's something I'm missing, please check carefully. I also only looked at the bytecode, not real execution.
