### ISSUE TITLE
Add arduino nano

### ISSUE THREAD

**Issue by moritz31** [Rahix/avr-hal#64]
What would be the way to go to add an arduino nano ?

**Comment by lights0123** [comment]
The Arduino Nano is identical to the Arduino Uno in every way except physical form factor, so you can just pretend it's an Uno and use its crate. I don't know if @Rahix would prefer to create a dedicated Nano crate though, even if it just re-exports everything from the Uno.

**Comment by D1plo1d** [comment]
This is for the Arduino Nano but not the Arduino Nano Every correct?

For future Googler's of Rust + Arduino Nano I think it's this one that work: https://store.arduino.cc/usa/arduino-nano

**Comment by Rahix** [comment]
@D1plo1d, yes the _Arduino Nano Every_ has a completely different MCU (`ATmega4809`) so it is not compatible.

**Comment by Rahix** [comment]
> The Arduino Nano is identical to the Arduino Uno in every way (well, at least in regards to the ATMega328) except physical form factor, so you can just pretend it's an Uno and use its crate. I don't know if @Rahix would prefer to create a dedicated Nano crate though, even if it just re-exports everything from the Uno.

I've thought about this for a bit and here's what I would suggest:  For boards which are reasonably similar, we only have a single crate; `arduino-uno` in this case.  For each 'compatible' board, this crate gets a cargo-feature to enable any slight changes as necessary.  E.g. Arduino Nano exposes `ADC6` and `ADC7` which don't exist on Arduino Uno.

If this turns out to be too confusing, we can still add a "wrapper crate" which just exposes everything from `arduino-uno` and enables said feature by default.

**Comment by Rahix** [comment]
Arduino Nano is now "officially" supported in the `arduino-uno` crate via the `arduino-nano` feature flag.  Here's the docs: https://rahix.github.io/avr-hal/arduino_uno/#compatible-boards
